# Generated by Django 4.2.14 on 2024-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
